### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wvpoi-site#1]
Hi Alexey!
The last files are from 5 months ago. Do you plan to update them from time to time?
You could use a Labs instance to do the work automatically.
Good luck! :-)

**Comment by baturin** [comment]
Hi Nicolas!

I will try to do an update this week. What do you mean by "Labs instance"?
BTW, have you seen a new Wikivoyage site feature - download per-page GPX
file?

2015-07-10 13:57 GMT+06:00 Nicolas Raoul notifications@github.com:

**Comment by baturin** [comment]
Updated.

**Comment by nicolas-raoul** [comment]
Updating manually is time-consuming and non-optimal.

Labs can provide you with a free server for running Wikimedia-related tasks.
Sign up at https://wikitech.wikimedia.org/w/index.php?title=Special:UserLogin&returnto=Help%3AGetting+Started&type=signup
It is just a normal Ubuntu server, so you can git clone your tool and set up cron to run it every 2 weeks (or even better: run everyday a script that checks whether a new Wikivoyage dump is available or not, and run your tool only when a new dump is available. [example](https://github.com/nicolas-raoul/wikivoyage2osm/blob/master/all.sh)).
I have set up such a tool in the past, so please feel free to ask me any question about that.

**Comment by baturin** [comment]
Hi Nicolas!

I've created a site for Wikivoyage POI dumps and set up a cron job there. It's not on Wikimedia servers, just my own VPS on my domain. Here is the site: http://wvpoi.batalex.ru/. The cron job checks for new Wikivoyage dumps on a daily basis.

**Comment by nicolas-raoul** [comment]
wikivoyage-listings-en-20151002.xml.bz2 contains 68,282 listings (`grep "node id" ~/Downloads/wikivoyage-listings-en-20151002.xml | wc -l`).
In comparizon, enwikivoyage-20150901-listings.csv from wikivoyage2osm contains 242,996 listings.
Is there a reason for that? Maybe listings with no latitude/longitude are ignored?

**Comment by baturin** [comment]
Yes, listings with no latitude/longitude are ignored, I did not find them useful. And of course there could be bugs, I have not tested on EN language much.

**Comment by baturin** [comment]
Fixed, now listings with absent positional data are not ignored for CSV and SQL.
