### ISSUE TITLE
Command-line option to also include POIs with no latitude/longitude

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wvpoi-site#2]
I am interested in all POIs, even those with no lat/lon...
Would it be possible to have a command-line option like `-all` that would include those too?
I can implement it.

**Comment by baturin** [comment]
For which formats do you want to add it? I think it makes no sense to add it to OBF, but it could be useful for all the others. May be even there should be no option, so listings without position data are always added.

**Comment by nicolas-raoul** [comment]
I need it only for CSV.

**Comment by baturin** [comment]
Ok, I think it would be fine.

**Comment by baturin** [comment]
I think that issue is already fixed - now all listings are put into CSV.
